# ── Build stage ─────────────────────────────────────────────────────────────
FROM node:22-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps

COPY . .

ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_CONTACT_EMAIL
ARG VITE_DESK_EMAIL
ARG VITE_WHATSAPP_NUMBER
ARG VITE_OFFICE_LOCATION
ARG VITE_BASE_PRICE_USD
ARG VITE_BASE_PRICE_ETB
ARG VITE_STAT_PROJECTS
ARG VITE_STAT_DELIVERY
ARG VITE_STAT_RATING
ARG VITE_STAT_COUNTRIES
ARG VITE_EXCHANGE_RATES
ARG VITE_PRICE_WRITING_BASIC
ARG VITE_PRICE_WRITING_STANDARD
ARG VITE_PRICE_WRITING_PREMIUM
ARG VITE_PRICE_CODING_BASIC
ARG VITE_PRICE_CODING_STANDARD
ARG VITE_PRICE_CODING_PREMIUM
ARG VITE_PRICE_ENGINEERING_BASIC
ARG VITE_PRICE_ENGINEERING_STANDARD
ARG VITE_PRICE_ENGINEERING_PREMIUM
ARG VITE_PRICE_DATA_BASIC
ARG VITE_PRICE_DATA_STANDARD
ARG VITE_PRICE_DATA_PREMIUM
ARG VITE_PRICE_STEM_BASIC
ARG VITE_PRICE_STEM_STANDARD
ARG VITE_PRICE_STEM_PREMIUM
ARG VITE_PRICE_ETB_WRITING_BASIC
ARG VITE_PRICE_ETB_WRITING_STANDARD
ARG VITE_PRICE_ETB_WRITING_PREMIUM
ARG VITE_PRICE_ETB_CODING_BASIC
ARG VITE_PRICE_ETB_CODING_STANDARD
ARG VITE_PRICE_ETB_CODING_PREMIUM
ARG VITE_PRICE_ETB_ENGINEERING_BASIC
ARG VITE_PRICE_ETB_ENGINEERING_STANDARD
ARG VITE_PRICE_ETB_ENGINEERING_PREMIUM
ARG VITE_PRICE_ETB_DATA_BASIC
ARG VITE_PRICE_ETB_DATA_STANDARD
ARG VITE_PRICE_ETB_DATA_PREMIUM
ARG VITE_PRICE_ETB_STEM_BASIC
ARG VITE_PRICE_ETB_STEM_STANDARD
ARG VITE_PRICE_ETB_STEM_PREMIUM

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_CONTACT_EMAIL=$VITE_CONTACT_EMAIL
ENV VITE_DESK_EMAIL=$VITE_DESK_EMAIL
ENV VITE_WHATSAPP_NUMBER=$VITE_WHATSAPP_NUMBER
ENV VITE_OFFICE_LOCATION=$VITE_OFFICE_LOCATION
ENV VITE_BASE_PRICE_USD=$VITE_BASE_PRICE_USD
ENV VITE_BASE_PRICE_ETB=$VITE_BASE_PRICE_ETB
ENV VITE_STAT_PROJECTS=$VITE_STAT_PROJECTS
ENV VITE_STAT_DELIVERY=$VITE_STAT_DELIVERY
ENV VITE_STAT_RATING=$VITE_STAT_RATING
ENV VITE_STAT_COUNTRIES=$VITE_STAT_COUNTRIES
ENV VITE_EXCHANGE_RATES=$VITE_EXCHANGE_RATES
ENV VITE_PRICE_WRITING_BASIC=$VITE_PRICE_WRITING_BASIC
ENV VITE_PRICE_WRITING_STANDARD=$VITE_PRICE_WRITING_STANDARD
ENV VITE_PRICE_WRITING_PREMIUM=$VITE_PRICE_WRITING_PREMIUM
ENV VITE_PRICE_CODING_BASIC=$VITE_PRICE_CODING_BASIC
ENV VITE_PRICE_CODING_STANDARD=$VITE_PRICE_CODING_STANDARD
ENV VITE_PRICE_CODING_PREMIUM=$VITE_PRICE_CODING_PREMIUM
ENV VITE_PRICE_ENGINEERING_BASIC=$VITE_PRICE_ENGINEERING_BASIC
ENV VITE_PRICE_ENGINEERING_STANDARD=$VITE_PRICE_ENGINEERING_STANDARD
ENV VITE_PRICE_ENGINEERING_PREMIUM=$VITE_PRICE_ENGINEERING_PREMIUM
ENV VITE_PRICE_DATA_BASIC=$VITE_PRICE_DATA_BASIC
ENV VITE_PRICE_DATA_STANDARD=$VITE_PRICE_DATA_STANDARD
ENV VITE_PRICE_DATA_PREMIUM=$VITE_PRICE_DATA_PREMIUM
ENV VITE_PRICE_STEM_BASIC=$VITE_PRICE_STEM_BASIC
ENV VITE_PRICE_STEM_STANDARD=$VITE_PRICE_STEM_STANDARD
ENV VITE_PRICE_STEM_PREMIUM=$VITE_PRICE_STEM_PREMIUM
ENV VITE_PRICE_ETB_WRITING_BASIC=$VITE_PRICE_ETB_WRITING_BASIC
ENV VITE_PRICE_ETB_WRITING_STANDARD=$VITE_PRICE_ETB_WRITING_STANDARD
ENV VITE_PRICE_ETB_WRITING_PREMIUM=$VITE_PRICE_ETB_WRITING_PREMIUM
ENV VITE_PRICE_ETB_CODING_BASIC=$VITE_PRICE_ETB_CODING_BASIC
ENV VITE_PRICE_ETB_CODING_STANDARD=$VITE_PRICE_ETB_CODING_STANDARD
ENV VITE_PRICE_ETB_CODING_PREMIUM=$VITE_PRICE_ETB_CODING_PREMIUM
ENV VITE_PRICE_ETB_ENGINEERING_BASIC=$VITE_PRICE_ETB_ENGINEERING_BASIC
ENV VITE_PRICE_ETB_ENGINEERING_STANDARD=$VITE_PRICE_ETB_ENGINEERING_STANDARD
ENV VITE_PRICE_ETB_ENGINEERING_PREMIUM=$VITE_PRICE_ETB_ENGINEERING_PREMIUM
ENV VITE_PRICE_ETB_DATA_BASIC=$VITE_PRICE_ETB_DATA_BASIC
ENV VITE_PRICE_ETB_DATA_STANDARD=$VITE_PRICE_ETB_DATA_STANDARD
ENV VITE_PRICE_ETB_DATA_PREMIUM=$VITE_PRICE_ETB_DATA_PREMIUM
ENV VITE_PRICE_ETB_STEM_BASIC=$VITE_PRICE_ETB_STEM_BASIC
ENV VITE_PRICE_ETB_STEM_STANDARD=$VITE_PRICE_ETB_STEM_STANDARD
ENV VITE_PRICE_ETB_STEM_PREMIUM=$VITE_PRICE_ETB_STEM_PREMIUM

RUN npm run build

# ── Production stage ───────────────────────────────────────────────────────
FROM node:22-alpine AS runner
WORKDIR /app

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY package.json package-lock.json ./
RUN npm ci --omit=dev --legacy-peer-deps

COPY --from=builder /app/dist ./dist

ENV NODE_ENV=production
ENV PORT=80
EXPOSE 80

USER appuser

CMD ["node", "dist/server.cjs"]
